# patterns.py

patterns_mavi = [
    r'\buchha ma v\b',
    r'\bma v\b',
    r'\bma vi\b',
    r'\bhigh school\b',
    r'\bsecondary\s*(\w*\s*)?school\b',
    r'\bsec\. school\b',
    r'\bma v\b',
    r'\bhigh school\b',
    r'\bsecondary school\b',
    r'\bmadhyamik\b',
    r'\bma vi\.\b',
    r'\bma vi\b',
    r'\bmavi\b',
    r'\bmv\b',
    r'\bma vidyalaya\b',
    r'\bsecondary\b',
    r'\bma विi\b',
    r'\bmav\b',
    r'\bseccondary school\b',
    r'\bsecondray school\b',
    r'\bsecondry school\b',
    r'\bs school\b',
    r'\buchha mv\b',
    r'\bseccondary school\b',
    r'\bmadhyamik vidyalay\b',
    r'\bmadhyamik bidhyalaya\b',
    r'\bma bi\b',
    r'\bsec school\b',
    r'\bsecodary school\b'
]

patterns_nimavi = [
    r'\bni ma v\b',
    r'\bni mi v\b'
]

patterns_pravi = [
    r'\bpra v\b',
    r'\bprimary school\b',
    r'\bpra vi\b',
    r'\bprathamic bidyalaya\b',
    r'\bprathamik bidhyalaya\b',
    r'\bprathamik vidhyalaya\b',
    r'\bpra v\b',
    r'\bprimary school\b',
    r'\bpra vi\b',
    r'\bpvt ltd\b',
    r'\bप्रा विi\b',
    r'\badharbhut pra v\b',
    r'\bpraimary school\b',
    r'\bpremary\b',
    r'\bpr v\b',
    r'\bprathamic vidhyalaya\b',
    r'\bprathamik vidhayalaya\b',
    r'\bprv\b'
]

patterns_avi = [
    r'\bbasic school\b',
    r'\badharbhut vidyalaya\b',
    r'\baa vi\b',
    r'\badharbhut vidhyalaya\b',
    r'\baa v\b',
    r'\badharbhut bidhyalaya\b',
    r'\badharbhut school\b',
    r'\baadharbhut school\b',
    r'\badhar v\b',
    r'\badharbhut, v\b',
    r'\bbasic level school\b',
    r'\baadharbhut viddhyalaya\b',
    r'\badharbhut bidyalay\b',
    r'\baadharbhut bidyalaya\b',
    r'\baadharbhut vidyalay\b',
    r'\baadharvut bidyalaya\b',
    r'\bbasic v\b',
    r'\badharbhut bidhyalaya\b',
    r'\badharbhut bidhyalay\b',
    r'\bbasic chool\b',
    r'\baadharvut vidyalaya\b',
    r'\baadharbhut vidhalaya\b',
    r'\badharbhut vidhyalaya\b',
    r'\badharbhut vidyalaya\b',
    r'\baa vi\b',
    r'\baa v\b',
    r'\baadharvut school\b',
    r'\badharbhoot vidhyalaya\b',
    r'\baadharbhut vidhyalaya\b',
    r'\badharbhut v\b',
    r'\bpre primary school\b',
    r'\badharbhoot v\b',
    r'\bbasic school\b',
    r'\baa\. v\b',
    r'\bbasic schoo\b',
    r'\baa\. vi\.\b',
    r'\baadharvut vidyalaya\b',
    r'\bpre primary school\b',
    r'\bpre school\b',
    r'\bBesic School\b',
    r'\bAdharbhut Vidhalaya\b',
    r'\bAadharbhut Vidyalaya\b',
    r'\bAadharbhut vidhyalaya\b',
    r'\badharbhoot v\b',
    r'\badhar v\b',
    r'\baa bi\b',
    r'\baadharbhut bidhyalaya\b',
    r'\bbasic scool\b',
    r'\bbasick school\b',
    r'\baadharbhut school\b',
    r'\badharbhut school\b',
    r'\bbasic level school\b',
    r'\baadharbhut vidyalaya\b',
    r'\badharbhut bidyalaya\b',
    r'\badharvut v\b',
    r'\badharbhut vidyalay\b',
    r'\badharbhut vidyalayai\b',
    r'\badhar vi\b',
    r'\bbasic cshool\b',
    r'\badharbhut vidayalay\b',
    r'\badharbhut bidhalaya\b',
    r'\baadharbhut bidhalaya\b',
    r'\baadharbhut bidhalaya\b',
    r'\badarbhut bidlaya\b',
    r'\bbesic school\b',
    r'\bbasic shool\b',
    r'\baadarbhut vidyalay\b',
    r'\baadharbhoot vidyalaya\b',
    r'\bbisic schoo\b',
    r'\baadharvut v\b',
    r'\badharbhut biddhyalaya\b',
    r'\badharboot vidyalaya\b',
    r'\badharvut vidyalaya\b',
    r'\badharbhoot vidhylaya\b',
    r'\bbasicschool\b',
    r'\badharbhoot vidyalaya\b',
    r'\badharbhut vidhalaya\b',
    r'\badharvut vidhyalaya\b',
    r'\badharvut school\b',
    r'\baadharboot school\b',
    r'\baadharbhut vidhayala\b',
    r'\baadharbhut biddhyalaya\b',
    r'\baadharbhut vidhayalay\b',
    r'\bAadharvut Vidhyalay\b',
    r'\badharbhut viddyala\b',
    r'\baabi\b',
    r'\bmadyamika vidyalaya\b',
    r'\bseconadary school\b',
    r'\baadharvut vidhyalaya\b',
    r'\badharbhut viddyalaya\b',
    r'\badharhhut school\b',
    r'\bm v\b',
    r'\badharbhut bidyalya\b',
    r'\baavi\b',
    r'\baadharvut vidhyalaya\b',
    r'\badharbhut bidyalya\b',
    r'\badharvut vi\b',
    r'\baadhabhut school\b',
    r'\baadharvhut schoo\b',
    r'\baadharbut v\b',
    r'\baadharbhut bidhyalay\b',
    r'\baadharvutschool\b',
    r'\badharvut biddyalaya\b',
    r'\badharbhut vidhvalaya\b',
    r'\baadharvhut school\b',
    r'\baadharvut vidhyalay\b',
    r'\baadharbhut viddhyalaya\b',
    r'\bbasic level school\b',
    r'\badharbhut vidhlaya\b',
    r'\badharbhut vidhyalay\b',
    r'\baadharbhut v\b',
    r'\baav\b',
    r'\baadharvut vidhyalay\b'
]
